myDF <- read.csv("/class/datamine/data/flights/2019.csv")
myDF <- read.csv("http://stat-computing.org/dataexpo/2009/airports.csv")
dim(myDF)
head(myDF)
names(myDF)
myDF$location <- paste(myDF$city, myDF$state)
head(myDF)
names(myDF)
tail(sort(table(myDF$location)),5)
#The four cities with the most airports are Indianapolis IN, Miami FL, New York NY, and Houston TX.
myDF <-read.csv("https://www1.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf")
dim(myDF)
head(myDF)
names(myDF)
mean(myDF$fare)
mean(myDF$passenger)
data <-read.csv("https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv")
dim(data)
head(data)
data$LocationID <- paste(data$Borough)
head(data)
names(data)
tail(sort(table(data$LocationID)) ,1)
#The most popular pickup location is Queens. It is in east New York
myDF <- read.delim("/class/datamine/data/election/itcont2020.txt", sep="|")
#It would be confusing separating data that belongs to each individual.
dim(myDF)
head(myDF)
names(myDF)
myDF$location <- paste(myDF$CITY, myDF$STATE)
head(myDF)
names(myDF)
tail(sort(table(myDF$location)),5)
#The city with the largest number of donations is New York, NY.